training-net/src/Controllers/HelloWorldController.cs
using System.Globalization;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Localization;

namespace training_net.Controllers
{
    public class HelloWorldController : Controller
    {
        private readonly IHtmlLocalizer<HelloWorldController> _localizer;

        public HelloWorldController(IHtmlLocalizer<HelloWorldController> localizer)
        {
            this._localizer = localizer;
        }

        public IHtmlLocalizer Localizer
        {
            get { return this._localizer; }
        }

        [Authorize]
        public IActionResult Index()
        {
            ViewData["Title"] = Localizer["HelloWorldTitle"].Value;            
            ViewData["Paragraph"] = Localizer["HelloWorldParagraph"].Value;
            return View();
        }
    }
}

training-net/src/Views/Shared/_AddEditForm.cshtml
@using Microsoft.AspNetCore.Mvc.Localization

@model training_net.Models.Views.MovieViewModel

@inject IViewLocalizer Localizer

<h2>@Localizer["MovieEditTitle"].Value</h2>
<p>@Localizer["MovieEditParagraph"].Value</p>

<form asp-action="Edit">
    <div class="form-horizontal">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <input type="hidden" asp-for="ID" />
        <div class="form-group">
            <label  asp-for="Genre" class="control-label col-md-2"></label>
            <div class="col-md-10">
                <input asp-for="Genre" class="form-control" type="text" id="Genre" name="Genre"/>
                <span asp-validation-for="Genre" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label  asp-for="Price" class="control-label col-md-2"></label>
            <div class="col-md-10">
                <input asp-for="Price" class="form-control" type="text" id="Price" name="Price"/>
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label  asp-for="ReleaseDate" class="control-label col-md-2"></label>
            <div class="col-md-10">
                <input asp-for="ReleaseDate" class="form-control" type="date" id="ReleaseDate" name="ReleaseDate"/>
                <span asp-validation-for="ReleaseDate" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label  asp-for="Title" class="control-label col-md-2"></label>
            <div class="col-md-10">
                <input asp-for="Title" class="form-control" type="text" id="Title" name="Title"/>
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="@ViewData["btnText"]" class="btn btn-default" />
            </div>
        </div>
    </div>
</form>

<div>
<a asp-action="Index">@Localizer["BackToList"].Value</a>
</div>

training-net/src/Views/Shared/_Details.cshtml
@using Microsoft.AspNetCore.Mvc.Localization
@inject IViewLocalizer Localizer
@model training_net.Models.Views.MovieViewModel

<h2>@ViewData["DetailsDeleteTitle"]</h2>

<div>
    <h4>@Localizer["Movie"]</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Localizer["Title"]
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt>
            @Localizer["Genre"]
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Genre)
        </dd>
        <dt>
            @Localizer["Price"]
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>
        <dt>
            @Localizer["ReleaseDate"]
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ReleaseDate)
        </dd>
        <dt>
            @Localizer["Rating"]
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Rating)
        </dd>
    </dl>
</div>

training-net/src/Views/Shared/_Form.cshtml
@using Microsoft.AspNetCore.Mvc.Localization
@model training_net.Models.Views.MovieViewModel
@inject IViewLocalizer Localizer

<h2>@ViewData["AddEditTitle"]</h2>
<p>@ViewData["AddEditPar"]</p>

<form asp-action="@ViewData["FormAction"]">
    <div class="form-horizontal">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <input type="hidden" asp-for="Id" />
        <div class="form-group">
            <label  asp-for="Title" class="control-label col-md-2">@Localizer["Title"]</label>
            <div class="col-md-10">
                <input asp-for="Title" class="form-control" type="text" id="Title" name="Title"/>
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label  asp-for="Genre" class="control-label col-md-2">@Localizer["Genre"]</label>
            <div class="col-md-10">
                <input asp-for="Genre" class="form-control" type="text" id="Genre" name="Genre"/>
                <span asp-validation-for="Genre" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label  asp-for="Price" class="control-label col-md-2">@Localizer["Price"]</label>
            <div class="col-md-10">
                <input asp-for="Price" class="form-control" type="text" id="Price" name="Price"/>
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label  asp-for="ReleaseDate" class="control-label col-md-2">@Localizer["ReleaseDate"]</label>
            <div class="col-md-10">
                <input asp-for="ReleaseDate" class="form-control" type="date" id="ReleaseDate" name="ReleaseDate"/>
                <span asp-validation-for="ReleaseDate" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label  asp-for="Rating" class="control-label col-md-2">@Localizer["Rating"]</label>
            <div class="col-md-10">
                <input asp-for="Rating" class="form-control" type="text" id="Rating" name="Rating"/>
                <span asp-validation-for="Rating" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="@ViewData["btnText"]" class="btn btn-default" />
            </div>
        </div>
    </div>
</form>

<div>
    <a asp-action="Index">@Localizer["BackToList"].Value</a>
</div>

training-net/src/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Mvc.Localization
@using System.Globalization

@inject IViewLocalizer Localizer

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - training_net</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">training_net</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
                    <li><a asp-area="" asp-controller="HelloWorld" asp-action="Index">@Localizer["HelloWorldButton"]</a></li>
                    <li><a asp-area="" asp-controller="Movie" asp-action="Index">@Localizer["MovieControllerTitle"]</a></li>
                    </ul>
                    @await Html.PartialAsync("_LoginPartial")
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - training_net</p>
        </footer>
    </div>

    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>